config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root 'rooms#index'
  post '/',                     to: 'rooms#generate'
  get '/new',                to: 'rooms#generate'
  get '/:room_session', to: 'rooms#show'
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def show
    @room_session = params[:room_session]
  end

  def generate
    sample_pool = [*"a".."z"] + [*"0".."9"]
    room_session = sample_pool.sample(6).join("")
    redirect_to "/#{room_session}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  def show
    authorize! :read, @user
  end

  def edit
    authorize! :update, @user
  end

  def update
    authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to root_url, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ]
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<div id="fade">

  <h1>Haunted</h1>

    <div id="welcome">

      <%= form_for :user do |f| %>
        <h2>welcome</h2>

        what is your name?<br>

        <%= f.text_field :name %><br>

        or<br>

        <div id="devise"><%= render 'devise/menu/registration_items' %>/
        <%= render 'devise/menu/login_items' %></div>

        <%= button_to "New Game", rooms_path, :class =>"button", method: :get %>
      <% end %>

    </div>

    <br>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Haunted</title>

  <%= stylesheet_link_tag 'application', 'vex', 'vex-theme-wireframe', media: '(min-width: 900px)', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'vex', 'vex-theme-wireframe', media: '(max-width: 900px)', 'data-turbolinks-track' => true %>

  <script language="JavaScript" type = "text/Javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://cdn.firebase.com/js/client/1.0.19/firebase.js"></script>

  <%= javascript_include_tag ('application'), 'data-turbolinks-track' => true %>

  <script>vex.defaultOptions.className = 'vex-theme-wireframe';</script>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <%= yield %>
  </div id="container">

</body>
</html>

app/views/rooms/index.html.erb
<%= javascript_include_tag ('home'), 'data-turbolinks-track' => true %>
<div id="fade">
  <h1>Haunted</h1>
  <div id="welcome">
    <%= button_to "New Game", new_path, :class =>"button", method: :get %>
    <div id="devise">
      <%= render 'devise/menu/registration_items' %> or 
      <%= render 'devise/menu/login_items' %>
    </div>

    <div id="social-media">
      <a href="/users/auth/facebook"><img src='/images/facebook.png' width="40"></a>
      <a href="/users/auth/twitter"><img src='/images/twitter.png' width="40"></a>
    </div>

  </div>
  <br>
</div>

app/views/rooms/show.html.erb
<input type="hidden" id="room-session" value="<%= @room_session %>">

<div id="chat-widget" class="desktop-only">
  <h2><a href="http://haunted-game.herokuapp.com/">Haunted</a></h2>
  <div id="panel">
    <img src="/sidebarghost.png"><br>
    <button id="instructions-button">Instructions</button>
    <button id="aboutus-button">About Us</button>
  </div>

  <div id="chat">
  <h3>Chat</h3>
  <div id="msg-output"></div>
    <form id="chat-form">
      <input type="text" id="user-name" value="Anonymous"></input>
      <input type="text" id="msg-input" placeholder="Message" required></input>
      <input type="submit" id="send" value="Send"></input>
    </form>
  </div>
</div>

<%= javascript_include_tag "main.js" %>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>